### ISSUE TITLE
Add advice what to do if macOS has no yarn and/or brew command

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#11]
Because this can occur in Nitro-Backend and Nitro-Web may one should add a section „General“ and set a link to it on both locations?

**Comment by FedericoEsparza** [comment]
Many might not have yarn installed, so I think adding the `npm install -g yarn` would be helpful.

Hyperlinking brew.sh would also be helpful.

However, like @roschaefer said in today's meeting, we have to draw a line somewhere, in terms of instructing people how to set up their local environment.
