### ISSUE TITLE
Add instructions to get Neo4j Desktop to work

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#12]
What to do to generate an empty database in Neo4j Desktop with the right password.
Instructions to seed the database!?
– yarn run db:seed
– yarn run db:reset

**Comment by roschaefer** [comment]
If your operating system does not have `yarn` or `node` installed, I would suggest to run everything within docker. Dependencies are a never ending problem. I would suggest to ask newcomers to install docker as the only dependency which will virtualize all the other dependencies and we can finally get rid of all the frustration.
![Dockerize all the dependencies](https://i.imgflip.com/2rcusg.jpg "Dockerize all the dependencies")

**Comment by Tirokk** [comment]
Sorry. As I stepped into the community meeting yesterday @roschaefer I just came from another job and had no time to read any mails etc. 😬

**Comment by roschaefer** [comment]
No problemo! @Tirokk
