### ISSUE TITLE
All tabs have title „Untitled“ - Error in file „edit_this_documentation.md“, under headline „Screenshot modification“

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#15]
I can not see why, at the moment.
Can somebody have a look?

**Comment by appinteractive** [comment]
What tabs? What are you referencing? Do you have a screenshot / url?

**Comment by Tirokk** [comment]
I have figured out that this problem comes via an auto substitution for quotation marks in my Safari browser on macOS. I fixed it in my pull request @appinteractive .
