### ISSUE TITLE
Add a Github fork/pull-request workflow reference

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#19]
Even may add an additional section for GitHub in the documentation?

I  think I found a good in: [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

**Comment by appinteractive** [comment]
Sure would be nice! Like a how to start, beginners section.

**Comment by Tirokk** [comment]
I have started working on it.

**Comment by mattwr18** [comment]
Can this be closed now that we are suggesting new developer's clone directly?
I will put in a `PR` to update the docs

**Comment by roschaefer** [comment]
As @mattwr18 pointed out, we favour to get in direct contact with us through [Discord](discordapp.com/invite/6ub73U3) and get write permissions to our repository. [KISS principle](https://en.wikipedia.org/wiki/KISS_principle). The only thing one could break is our staging environment - not terrible enough to for having restrictions on write permissions.
