### ISSUE TITLE
Add forking instructions in Web Installation

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#20]
… like in Backend installation documentation.
[https://github.com/Human-Connection/Nitro-Documentation/tree/master/backend/installation](https://github.com/Human-Connection/Nitro-Documentation/tree/master/backend/installation)

In web installation documentation is only cloning mentioned.

**Comment by mattwr18** [comment]
hey @Tirokk we have discussed this and because of the inability to access encrypted environment variables on the Travis build have decided to go with cloning directly. Gonna close this.
