### ISSUE TITLE
images for the Neo4j setup 

### ISSUE THREAD

**Issue by tansaku** [Human-Connection/Nitro-Documentation#22]
Would it make sense to have some images to help illustrate the Neo4j Desktop setup?  E.g.

![](https://dl.dropbox.com/s/hmnmt79uui4uxzd/Screenshot%202019-02-05%2009.43.52.png?dl=0)

**Comment by roschaefer** [comment]
Certainly!

**Comment by roschaefer** [comment]
@tansaku I'm closing this if you don't mind. It's a little to unspecific to keep this issue open.
