### ISSUE TITLE
Kubernetes link is broken

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Nitro-Documentation#24]
Broken link:
[https://github.com/Human-Connection/Nitro-Backend/tree/master/kubernetes](https://github.com/Human-Connection/Nitro-Backend/tree/master/kubernetes)

… on page:
https://docs.human-connection.org/nitro/backend/installation/docker

<img width="845" alt="bildschirmfoto 2019-02-13 um 05 45 50" src="https://user-images.githubusercontent.com/25344101/52688346-63d35d00-2f56-11e9-8e9c-cb8a809d6d14.png">

**Comment by appinteractive** [comment]
Should be now: https://github.com/Human-Connection/Nitro-Deployment

**Comment by Tirokk** [comment]
Okidoki ;-)

**Comment by appinteractive** [comment]
Will you fix it?

**Comment by Tirokk** [comment]
I fixed it already in my documentation for Docker I just working on, yes.
