### ISSUE TITLE
Neo4j link takes you to the enterprise version for Neo4j

### ISSUE THREAD

**Issue by Kachulio1** [Human-Connection/Nitro-Documentation#5]
<img width="841" alt="screen shot 2019-01-05 at 21 05 01" src="https://user-images.githubusercontent.com/22243090/50727628-8475ef00-112e-11e9-9abe-3beafb6c8c15.png">

I recommend changing the link to this [Neo4j](https://neo4j.com/artifact.php?name=neo4j-desktop-offline-1.1.13.dmg)
And placing it above the orange warning and reduce the paragraph a little bit.

**Comment by roschaefer** [comment]
@Kachulio1 it's a desktop installation file for macOS? I would add it to the paragraph and say it's for mac.

**Comment by Tirokk** [comment]
Is questionable and still pending if my Neo4j Desktop version is a 30 days test version or not …

**Comment by Tirokk** [comment]
My Neo4j Desktop version run out of the 30 days trail. So it is not a free version at all?
They say I can try it for longer if I register. But I think that won't change anything at the end …

Or did we just downloaded a wrong installation?

**Comment by appinteractive** [comment]
Just ignore it, you don’t need the enterprise version. It will still work.

**Comment by mattwr18** [comment]
Closing this as the documentation has been updated to show a screenshot of the Neo4j Desktop tab, although it would be nice for some mac users to try the community edition as @roschaefer and I haven't had any issues with it, and others have been blocked by various issues with Desktop, it seems.
