### ISSUE TITLE
When you run `yarn dev` before `yarn styleguide:build` command you get an Error

### ISSUE THREAD

**Issue by Kachulio1** [Human-Connection/Nitro-Documentation#6]
We should add `yarn styleguide:build` before `yarn dev` command

<img width="888" alt="screen shot 2019-01-05 at 21 49 49" src="https://user-images.githubusercontent.com/22243090/50727960-e4bb5f80-1133-11e9-8b20-5888ccd4978f.png">

This is the error

<img width="857" alt="screen shot 2019-01-05 at 21 36 10" src="https://i.imgur.com/8ZbFNnW.png">

**Comment by appinteractive** [comment]
The styleguide is a npm package now. No more build needed! Thanks guys!
